### ISSUE TITLE
Allow arbitrary install location and renaming of the installed application

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-mac-packager#11]
Right now everything goes into /Applications/QGIS.app

we want /Applications/QGIS-LTR.app QGIS-nightly.app or similar

**Comment by PeterPetrik** [comment]
This would be difficult since we have absolute paths for environment variables in "Info.plist", e.g. GRASS folder, PYTHONHOME, PYQGIS_START script, ...

**Comment by fgfletcher** [comment]
Being able to just rename the app would be very helpful.  During testing I often keep several QGIS versions in order to be able to switch between them for comparisons - e.g., QGIS_3_4_1_11-22.
Retrieving the running app name would allow its insertion into what now seem to be absolute paths dependent on finding "/Applications/QGIS.app".

**Comment by PeterPetrik** [comment]
@fgfletcher Thank you for comment, this is definitely on my plan.

> Retrieving the running app name would allow its insertion into what now seem to be absolute paths dependent on finding "/Applications/QGIS.app".

Wondering what exactly you propose, wrapping executable in some bash script? Or somehow possible to do in Info.plist? Do you have some example?

**Comment by PeterPetrik** [comment]
this is not possible technically with homebrew installation since some libraries have hardcoded paths in the compiled binaries.

**Comment by PeterPetrik** [comment]
The repository is no longer used, because QGIS Mac packaging system is moved under OSGEO/QGIS repository https://github.com/qgis/QGIS-Mac-Packager. Please reopen the issue in the new repository if it is still an issue
