### ISSUE TITLE
Support for MrSid

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mac-packager#45]
GDAL comes with all drivers with no licencing restriction, please add the non-free ones too.

**Comment by fgfletcher** [comment]
Support of MrSID files of vital importance because many critical files, e.g., ortho photos, are available only in that format.  At present the Lutra Consulting QGIS packages are not usable for real projects because of missing MrSID support.

The free MrSID SDK are available, but only by direct download from Extensis (https://www.extensis.com/support/developers). It is not clear (to me) if they would allow inclusion in generic QGIS distributions.

With the KyngChaos QGIS builds, MrSID is supported via a multi-step process after installation of QGIS:

1) the appropriate MrSID SDK is downloaded from Extensis

2) selected libraries from that SDK are copied into /Library/Application Support/GDAL/2.3/Libraries
  Library
    Application Support
      GDAL
        2.3
          etc
            Libraries
              liblti_lidar_dsdk.1.dylib
              libltidsdk.9.dylib
              libtbb.dylib
            PlugIns
              gdal_MrSID.dylib

3) An installer package from KyngChaos, (https://www.kyngchaos.com/files/software/frameworks/GDAL-MrSID_Plugin-2.3.2-1.dmg) installs two plugins:
 /Library/Application Support/GDAL/2.3/PlugIns/gdal_MG4Lidar.dylib
 /Library/Application Support/GDAL/2.3/PlugIns/gdal_MrSID.dylib

4) two command line (Terminal) commands are executed:

 sudo "/Volumes/MrSID GDAL Plugin/install tools/install_name_tool" -change libtbb.dylib @loader_path/libtbb.dylib -change @rpath/libtbb.dylib @loader_path/libtbb.dylib "/Library/Application Support/GDAL/2.1/Libraries/libltidsdk.9.dylib"

 sudo "/Volumes/MrSID GDAL Plugin/install tools/install_name_tool" -change libtbb.dylib @loader_path/libtbb.dylib -change @rpath/libtbb.dylib @loader_path/libtbb.dylib "/Library/Application Support/GDAL/2.1/Libraries/liblti_lidar_dsdk.1.dylib"


There is an urgent need for support of MrSID - whether by inclusion in Lutra's "all in one" distribution or via some post-QGIS-installation process equivalent to that described above.

Cordially,
Garth Fletcher

**Comment by saberraz** [comment]
https://trac.osgeo.org/gdal/wiki/MrSID

**Comment by saberraz** [comment]
Example data:
https://www.harita.gov.tr/english/images/urun/I33A1_MrSid.zip

**Comment by PeterPetrik** [comment]
https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/gdal2-mrsid.rb

https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/mrsid-sdk.rb

**Comment by saberraz** [comment]
License:
https://download.osgeo.org/osgeo4w/x86_64/release/gdal/gdal-dev/gdal-dev-mrsid/gdal-dev-mrsid-2.3.0-41911.pdf

**Comment by saberraz** [comment]
[license_mrsid.txt](https://github.com/lutraconsulting/qgis-mac-packager/files/2880661/license_mrsid.txt)

**Comment by PeterPetrik** [comment]
@fgfletcher @saberraz can you please test with https://www.dropbox.com/s/jnty3t88jbs7u0f/qgis_pr_final-3_4_4_20190220_045748.dmg?dl=0

**Comment by fgfletcher** [comment]
> @fgfletcher @saberraz can you please test with https://www.dropbox.com/s/jnty3t88jbs7u0f/qgis_pr_final-3_4_4_20190220_045748.dmg?dl=0

YES YES YES !

MrSID now works perfectly.

Thank you very much for this wonderful enhancement!
-- 
Garth Fletcher, President, JacqCAD International
288 Marcel Road, Mason, NH 03048-4704
(603) 878-4749
JacqCAD MASTER website: www.JacqCAD.com

**Comment by saberraz** [comment]
@fgfletcher we tried to stick with Apple philosophy for our 1-click installer: everything should just work :)
